// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PersonData struct {
	First    *string `json:"first"`
	Last     *string `json:"last"`
	GamerTag *string `json:"gamerTag"`
	Birthday *int    `json:"birthday"`
}

type Player struct {
	Data  *PersonData `json:"data"`
	Stats *StatBlock  `json:"stats"`
}

type StatBlock struct {
	Mental *int `json:"mental"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
