type PersonData {     
  first: String     
  last: String     
  gamerTag: String     
  birthday: Int 
}

type StatBlock {     
  mental: Int 
}

type Player {     
  data: PersonData     
  stats: StatBlock 
}