// Team object
type team {
  id: Int!
  owner: String!
  teamName: String!
  players: [Player!]!
  userID: Int!
  overallScore: Int
  coachID: Int
  money: Int
  fans: Int
}

query getTeam($playerID: Int!) {
    team(id: $playerID) {
      id: Int!
      owner: String!
      name: String!
      players: [Player!]!
      userID: Int!
      overallScore: Int
      coachID: Int
      money: Int
    }
}

// Player object
type PersonData {
  id: Int!
  first: String
  last: String
  gamerTag: String
  birthday: Int
}

type StatBlock {
  id: Int!
  mental: Int
  micro: Int
  macro: Int
}

type Player {
  id: Int!
  data: PersonData!
  stats: StatBlock!
  coachInstruction: Int!
}

query getPlayer($playerID: Int!) {
    player(id: $playerID) {
        id
        data
        stats
    }
}

// League

type league {
  id: Int!
  timeStarted: Date!
  teamsInLeague: [Int!]!
  leagueRank: String!
}



// Coach Instructions (List of Instructions Coach can give maybe be something you can unlock)
type coachInstruction {
  id: Int!
  instruction: String!
  Description: String!
}


// Match
type match {
  id: Int!
  players: [Int]
  status: String!
  overallRating: Int!
  enemyOverallRating: Int!
}
