const UPCOMING_MATCH_BORDER = "#4ca2cd";
const CURRENT_MATCH_BORDER = "#67B26F";

const LOADING_GRADIENT_TOP = "#67B26F";
const LOADING_GRADIENT_BOTTOM = "#4ca2cd";

export {
  UPCOMING_MATCH_BORDER,
  CURRENT_MATCH_BORDER,
  LOADING_GRADIENT_TOP,
  LOADING_GRADIENT_BOTTOM
};
